### ISSUE TITLE
Coud you please provide some bag file for testing this great package

### ISSUE THREAD

**Issue by weisongwen** [at-wat/neonavigation#110]
Dear @at-wat  

Thanks for your effort on this great package, Could you please provide some datesheet or bag file related to this package to test this package? 

Thanks a lot,
Best 
Welson

**Comment by at-wat** [comment]
👍

**Comment by brainhenry** [comment]
thanks for the help. my email address is 14108209d@connect.polyu.hk or brainhenry100@gmail.com

**Comment by at-wat** [comment]
@weisongwen I have added a launch file and sample map for a demonstration.
It is not easy to test with a bag file since the navigation works with the feedback from the environment according to the motion of the vehicle. So, I have added a launch file with the kinematics (not dynamics) simulation of the vehicle and simulated local costmap.

Please try it:
```shell
$ roslaunch neonavigation_launch demo.launch
```

**Comment by weisongwen** [comment]
Hi, @at-wat  
Thanks for your kind reply, I will test this first,
Best 
Welson

**Comment by at-wat** [comment]
Feel free to reopen if you have any related questions or requests.

**Comment by weisongwen** [comment]
Dear @at-wat 
Thanks for your kind information,

best 
Welson
